name: Perform Automated Tests and Linting
on: [push]
defaults:
  run:
    working-directory: ./vite-project
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        working-directory: .
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
  test:
    name: Vitest
    needs: setup
    steps:
      - name: Run tests
        run: npm run test
  lint:
    name: Lint
    needs: lint
    steps:
      - name: Run lint
        run: npm run lint
